import bilby
import parallel_bilby
import bilby_pipe
import bilby_pipe.bilbyargparser
from bilby_pipe.parser import StoreBoolean
from bilby_pipe.utils import nonestr, nonefloat, noneint
import argparse

from ..parser import _create_base_parser

def create_rapid_analysis_parser(prog, prog_version):
    base_parser = _create_base_parser(prog, prog_version)

    parser = bilby_pipe.bilbyargparser.BilbyArgParser(
        prog=prog,
        ignore_unknown_config_file_keys=False,
        allow_abbrev=False,
        add_help=True,
        parents=[base_parser]
    )

    parser.add("ini", type=str, is_config_file=True, help="Configuration ini file")

    # Dealing with multiple inputs, and possibly from different inference packages
    joint_input_parser = parser.add_argument_group(title="Joint input arguments", description="Specify multiple inputs")
    joint_input_parser.add(
        "--n-triggers",
        type=int,
        help="Number of triggers to be analyzed jointly"
    )
    joint_input_parser.add(
        "--trigger-ini-files",
        action="append",
        help=(
            "A list of configuration ini files for each trigger to be jointly analyzed, "
            "specified either by `trigger-ini-file=[PATH_1, PATH2]` or "
            "as command-line arguments by `--trigger-ini-files PATH1 --trigger-ini-files PATH2`"
        )
    )
    joint_input_parser.add(
        "--data-dump-files",
        action="append",
        help=(
            "A list of data dump files for each trigger, "
            "specified either by `data-dump-files=[FILE1, FILE2]` or "
            "as command-line arguments by `--data-dump-files FILE1 --data-dump-files FILE2`"
        )
    )
    joint_input_parser.add(
        "--result-files",
        action="append",
        help=(
            "A list of result files that were generated by bilby or parallel bilby"
            "for each trigger, specified either by `result-files=[FILE1, FILE2]` or "
            "as command-line arguments by `--result-files FILE1 --result-files FILE2`"
        )
    )
    joint_input_parser.add(
        "--inference-software",
        action="append",
        help=(
            "A list of inference software (either bilby or parallel_bilby) "
            "that were used to generate the result files given in the option "
            "--result-files, specified either by `inference-software=[PROGRAM1, PROGRAM2]` or "
            "as command-line arguments by `--inference-software PROGRAM1 --inference-software PROGRAM2`"
        )
    )

    output_parser = parser.add_argument_group(title="Output arguments", description="Specify the settings for output")
    output_parser.add(
        "--outdir",
        type=str,
        default="outdir",
        help="The output directory"
    )
    output_parser.add("--label", type=str, default="label", help="Output label")

    # Dealing with lensing speific prior
    lensing_prior_parser = parser.add_argument_group(title="Lensing prior arguments", description="Specify the prior settings for lensing analysis")
    lensing_prior_parser.add(
        "--common-parameters",
        action="append",
        help=(
            "A list of common parameters that are imposed to take the same value across different triggers, "
            "specified either by `common-parameters=[chirp_mass, mass_ratio]` or "
            "as command-line arguments by `--common-parameters chirp_mass --common-parameters mass_ratio`"
        )
    )
    lensing_prior_parser.add(
        "--lensing-prior-dict",
        type=nonestr,
        default=None,
        help=(
            "A dictionary of prior for image type."
            "Specified by lensing-prior-dict={image_type^(1) = 1, image_type^(2) = 2} for fixed image types, or "
            "lensing-prior-dict={image_type^(1)=hanabi.lensing.prior.DiscreteUniform(minimum=1, N=3), image_type^(2)=...} for discrete probability distribution. "
            "Note that setting this will override the priors used in the single-trigger results if the image type is sampled."
        )
    )

    analysis_setting_parser = parser.add_argument_group(title="Analysis setting arguments", description="Specify the analysis settings")
    analysis_setting_parser.add(
        "--request-cpus",
        type=int,
        default=1,
        help=(
            "Use multi-processing (default: 1). "
            "While this might decrease the wall time, turning this on will increase the "
            "memory usage drastically"
        )
    )
    analysis_setting_parser.add(
        "--symmetrize",
        default=True,
        action=StoreBoolean,
        help=(
            "Form symmetric pairs of given triggers (default: True). For example if there are "
            "two triggers, two runs will be launched: inferring trigger 2 condition "
            "on trigger 1; and inferring trigger 1 condition on trigger 2"
        )
    )  
    analysis_setting_parser.add(
        "--downsample",
        type=int,
        help="Use this many posterior samples instead of using all available"
    )
    analysis_setting_parser.add(
        "--time-marginalization",
        default=True,
        action=StoreBoolean,
        help="Turn on time marginalization (default: True)"
    )
    analysis_setting_parser.add(
        "--distance-marginalization",
        default=True,
        action=StoreBoolean,
        help="Turn on distance marginalization (default: True)"
    )
    analysis_setting_parser.add(
        "--waveform-cache",
        default=True,
        action=StoreBoolean,
        help="Enable waveform caching",
    )

    return parser